# Generated by Django 5.1.4 on 2025-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_audioprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='grade_levels',
            field=models.ManyToManyField(blank=True, related_name='skills', to='api.gradelevel'),
        ),
    ]
