# Generated by Django 5.1.4 on 2025-11-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_gradelevel_skill_grade_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexample',
            name='practiced_skills',
            field=models.ManyToManyField(blank=True, related_name='student_examples', to='api.skill'),
        ),
    ]
