# Generated by Django 5.1.4 on 2025-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_studentexample_practiced_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('OPERATION', 'Operation'), ('NUMBER_DOMAIN', 'Number Domain'), ('COMBINED', 'Combined')], max_length=50, null=True),
        ),
    ]
