# Generated by Django 5.1.4 on 2025-11-22 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_skill_level_alter_skill_skill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('language', models.CharField(choices=[('cs', 'Czech'), ('sk', 'Slovak'), ('en', 'English')], default='cs', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('OPERATION', 'Operation'), ('NUMBER_DOMAIN', 'Number Domain')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentexample',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='studentexample',
            name='anonymous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anonymoussession'),
        ),
        migrations.AddConstraint(
            model_name='studentexample',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('anonymous_session__isnull', False), _connector='OR'), name='student_or_session_required'),
        ),
    ]
