# Generated by Django 5.1.4 on 2025-11-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_anonymoussession_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('cs', 'Czech'), ('sk', 'Slovak'), ('en', 'English')], default='sk', max_length=2),
        ),
    ]
