# Generated by Django 5.1.4 on 2026-02-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_student_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussession',
            name='audio_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='student',
            name='audio_threshold',
            field=models.IntegerField(default=50),
        ),
    ]
