# Generated by Django 5.1.4 on 2026-03-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_anonymoussession_audio_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoussession',
            name='audio_threshold',
        ),
        migrations.RemoveField(
            model_name='student',
            name='audio_threshold',
        ),
        migrations.CreateModel(
            name='ExampleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('duration', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('speech', 'Speech'), ('text', 'Text')], default='speech', max_length=16)),
                ('input_type', models.CharField(blank=True, default='', max_length=32)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('action', models.CharField(choices=[('evaluated', 'Evaluated'), ('skipped', 'Skipped'), ('terminated', 'Terminated'), ('no_match', 'No Match'), ('error', 'Error')], default='evaluated', max_length=32)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, default='')),
                ('parsed_answer', models.CharField(blank=True, default='', max_length=255)),
                ('example_text', models.CharField(blank=True, default='', max_length=255)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=255)),
                ('audio_file_path', models.CharField(blank=True, default='', max_length=500)),
                ('audio_format', models.CharField(blank=True, default='', max_length=50)),
                ('practiced_skill_ids', models.JSONField(blank=True, default=list)),
                ('practiced_skill_names', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('anonymous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_attempts', to='api.anonymoussession')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='api.example')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_attempts', to='api.student')),
                ('student_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='api.studentexample')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='api_example_student_ca8b5d_idx'), models.Index(fields=['anonymous_session', 'created_at'], name='api_example_anonymo_43b539_idx'), models.Index(fields=['example', 'created_at'], name='api_example_example_18b8e5_idx')],
            },
        ),
    ]
