# Generated by Django 5.1.4 on 2026-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_anonymoussession_audio_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussession',
            name='audio_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='student',
            name='audio_threshold',
            field=models.IntegerField(default=50),
        ),
    ]
