# Generated by Django 5.1.4 on 2026-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_gamification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examplereport',
            new_name='api_example_student_fc0a53_idx',
            old_name='api_example_student_d44995_idx',
        ),
        migrations.RenameIndex(
            model_name='examplereport',
            new_name='api_example_anonymo_ade51f_idx',
            old_name='api_example_anonymo_6f4d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='examplereport',
            new_name='api_example_example_b1d559_idx',
            old_name='api_example_example_502d1d_idx',
        ),
        migrations.RenameIndex(
            model_name='surveyfeedback',
            new_name='api_surveyf_student_7cfd14_idx',
            old_name='api_surveyf_student_466689_idx',
        ),
        migrations.RenameIndex(
            model_name='surveyfeedback',
            new_name='api_surveyf_anonymo_ea3dc6_idx',
            old_name='api_surveyf_anonymo_5944f8_idx',
        ),
        migrations.RenameIndex(
            model_name='surveyfeedback',
            new_name='api_surveyf_questio_5b4b46_idx',
            old_name='api_surveyf_questio_11b2bb_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_change_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='badge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
