# Generated by Django 5.1.4 on 2026-03-21 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anonymoussession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
