# Generated by Django 5.1.4 on 2026-03-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_examplerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='owner_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_tasks', to='api.anonymoussession'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_tasks', to='api.student'),
        ),
        migrations.CreateModel(
            name='GeneratedTaskBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('grade_group', models.IntegerField(choices=[(1, 'Grades 1–3'), (2, 'Grades 4–6'), (3, 'Grades 7–9')])),
                ('generation_mode', models.CharField(choices=[('ai_free', 'AI Free Hand'), ('backend_generator', 'Backend Generator')], default='ai_free', max_length=20)),
                ('description', models.TextField()),
                ('parser_output', models.JSONField(blank=True, default=dict)),
                ('raw_json', models.JSONField()),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('survey_done', 'Survey Done'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='preview', max_length=20)),
                ('rejection_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_batch', to='api.task')),
                ('example_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_batches', to='api.examplerequest')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_batches', to='api.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTaskBatchSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_as_requested', models.BooleanField()),
                ('q2_solvable_display', models.BooleanField()),
                ('q3_difficulty', models.CharField(choices=[('easy', 'Ľahké'), ('ok', 'Primerané'), ('hard', 'Ťažké')], max_length=8)),
                ('q4_has_errors', models.BooleanField()),
                ('q5_satisfied', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='api.generatedtaskbatch')),
            ],
        ),
    ]
