# Generated by Django 5.1.4 on 2026-03-27 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_task_primary_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexample',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_examples', to='api.task'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('OPERATION', 'Operation'), ('NUMBER_DOMAIN', 'Number Domain'), ('TASK', 'Task')], max_length=50, null=True),
        ),
    ]
