# Generated by Django 5.1.4 on 2026-03-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_studentexample_task_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexample',
            name='practice_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
    ]
