# Generated by Django 5.1.4 on 2026-03-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_practice_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_mastery', models.FloatField(default=0.05)),
                ('fluency_mastery', models.FloatField(default=0.5)),
                ('example_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='api.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to='api.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'skill'], name='api_skillma_student_4279fd_idx')],
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
