# Generated by hand, mirroring Django 5.1's CreateModel output (no local Django available to autogenerate).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_example_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('mode', models.CharField(choices=[('1v1', '1v1'), ('2v2', '2v2')], max_length=3)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=7)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=8)),
                ('time_limit_seconds', models.IntegerField()),
                ('target_steps', models.IntegerField(default=8)),
                ('rope_position', models.IntegerField(default=0)),
                ('question_orders', models.JSONField(blank=True, default=dict)),
                ('winner_team', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_games', to='api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuelParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('slot', models.IntegerField(default=1)),
                ('display_name', models.CharField(max_length=64)),
                ('is_founder', models.BooleanField(default=False)),
                ('current_index', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('connected', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('anonymous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_participations', to='api.anonymoussession')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.duelgame')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_participations', to='api.student')),
            ],
            options={
                'ordering': ['team', 'slot'],
                'unique_together': {('game', 'team', 'slot')},
            },
        ),
        migrations.AddConstraint(
            model_name='duelparticipant',
            constraint=models.CheckConstraint(check=models.Q(student__isnull=False) | models.Q(anonymous_session__isnull=False), name='duel_participant_student_or_session_required'),
        ),
    ]
