# Generated by Django 5.1.4 on 2026-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_duelgame_duelparticipant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='duelparticipant',
            name='duel_participant_student_or_session_required',
        ),
        migrations.AddField(
            model_name='duelgame',
            name='bot_difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='duelgame',
            name='vs_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duelparticipant',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='duelparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('anonymous_session__isnull', False), ('is_bot', True), _connector='OR'), name='duel_participant_student_or_session_required'),
        ),
    ]
