# Generated by Django 5.1.4 on 2026-09-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_duelparticipant_duel_participant_student_or_session_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('question', 'Question'), ('review', 'Review'), ('finished', 'Finished')], default='waiting', max_length=8)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('current_question_index', models.IntegerField(default=0)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='api.task')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_games', to='api.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('connected', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('anonymous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_participations', to='api.anonymoussession')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.quizgame')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_participations', to='api.student')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('time_taken_ms', models.IntegerField()),
                ('points_awarded', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.example')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizparticipant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quizparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('anonymous_session__isnull', False), _connector='OR'), name='quiz_participant_student_or_session_required'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('participant', 'question_index')},
        ),
    ]
