# Generated by Django 5.1.4 on 2026-09-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_quizgame_quizparticipant_quizanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('source_attempts', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_insights', to='api.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='api.student')),
            ],
            options={
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
