# Generated by Django 5.1.4 on 2026-09-05 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_printevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TugOfWarGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=8)),
                ('end_mode', models.CharField(choices=[('time', 'Time limit'), ('target', 'First to target')], default='time', max_length=6)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('target_diff', models.IntegerField(blank=True, null=True)),
                ('max_team_size', models.IntegerField(default=30)),
                ('rope_position', models.IntegerField(default=0)),
                ('winner_team', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tug_of_war_games', to='api.task')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tug_of_war_games', to='api.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TugOfWarParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('display_name', models.CharField(max_length=64)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('current_index', models.IntegerField(default=0)),
                ('current_question_started_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('connected', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('anonymous_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tow_participations', to='api.anonymoussession')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.tugofwargame')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tow_participations', to='api.student')),
            ],
            options={
                'ordering': ['team', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TugOfWarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('time_taken_ms', models.IntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.example')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.tugofwarparticipant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tugofwarparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('student__isnull', False), ('anonymous_session__isnull', False), _connector='OR'), name='tow_participant_student_or_session_required'),
        ),
        migrations.AlterUniqueTogether(
            name='tugofwarparticipant',
            unique_together={('game', 'student', 'anonymous_session')},
        ),
    ]
