# Generated by Django 5.1.4 on 2026-09-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_tugofwargame_tugofwarparticipant_tugofwaranswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', 'Task generation'), ('insight', 'Student AI insight')], default='task', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_events', to='api.teacher')),
            ],
        ),
    ]
